---
- name: setup apache2 on all servers
  hosts: all
  become: true
  vars:
    apache2_version: 2.4.41


  tasks:
  - name: install apache2 to server
    command: apt install apache2 -y



  - name: start apache2
    service:
      name: apache2
      enabled: yes
      state: started


  - name: Get apache2 installed version
    command: apache2 -v
    register: apache2_version

  - name: print apache2 version
    debug:
      msg: "The current version of apache2 is {{apache2_version}}"

  - name: Get the status of apache2 service
    command: systemctl status apache2

  - name: set timezone
    command: timedatectl set-timezone Africa/Lagos

  - name: Get status of timezone
    command: timedatectl