- hosts: all
  become: yes
  become_method: sudo
  gather_facts: false
  tasks:
    - include_role:
        name: sshkey

- hosts: all
  become: yes
  become_method: sudo
  gather_facts: false
  tasks:
    - include_role:
        name: php